[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
# logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
# async
tokio = { workspace = true }
# mqtt client
rumqttc = { workspace = true }
# additional dependencies
once_cell = { workspace = true }
